/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;


import Tools.KoneksiDB;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author acer
 */
public class Frmenu extends javax.swing.JFrame {
    KoneksiDB getCnn = new KoneksiDB();
    Connection _Cnn;
    
    //tabel User
    String vid_user, vnama_user, vpass, vlev_user;
    String sqlselect;
    IfrLapMahasiswa frlapmahasiswa;
    /**
     * Creates new form frmenu
     */
    public Frmenu() {
        initComponents();
        
        this.setExtendedState(this.getExtendedState () | Frmenu.MAXIMIZED_BOTH);
        disabledMenu();
        txtIdUser.requestFocus(true);
        
    }

    private void disabledMenu(){ // method yag membuat menjadi disable ketika pertam kali di jalankan
        mnSystem.setEnabled(false);
        mnMaster.setEnabled(false);
        mnMahasiswa.setEnabled(false);
    }
    private void enabledMenu(){ // method yang membuat menjadi enable ketika pertama kali di jalankan / menu yanng klik aktif
        mnSystem.setEnabled(true);
        mnMaster.setEnabled(true);
        mnMahasiswa.setEnabled(true);
    }
    void userAdministrator(){ // method yang membuat menjadi enable ketika pertama kali di jalankan / menu yanng klik aktif
        mnSystem.setEnabled(true);
        mnMaster.setEnabled(true);
        mnMahasiswa.setEnabled(true);
    }
    void userKemahasiswaan(){ // method yang membuat menjadi enable ketika pertama kali di jalankan / menu yanng klik aktif
        mnSystem.setEnabled(true);
        mnUser.setText("Ubah Password");
        mnMaster.setEnabled(true);
        mnMahasiswa.setEnabled(true);
    }
    
    private void aksilogin(){
        if(txtIdUser.getText().equals("")|| txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Id User dan Password belum di isi");
        }else{
            vid_user = txtIdUser.getText(); //memberikan nilai pada variabel vid_user
            vpass = txtPassword.getText();
            try{
                _Cnn = null; //mengkosongkan koneksi dan cn merupakan object dari koneksiDB
                _Cnn = getCnn.getConnection();
                sqlselect = "select * from tb_user where id_user = '"+vid_user+"'"
                        + " and pass =md5( '"+vpass+"') ";
                Statement stat = _Cnn.createStatement(); ///membuat statement query
                ResultSet res = stat.executeQuery(sqlselect); // menjalankan query harus menggunakan result pada query select
                if(res.first()){ //jika hasil (query select) ditemukan
                    vlev_user = res.getString("lev_user"); //memberkan nilai pada lev_user dari hasil query select dari kolom lev_user
                    vnama_user = res.getString("nama_user");
                    lblKeterangan.setText("ID. User:" +vid_user+" - "+vnama_user+
                            " | Lev.User :"+vlev_user);
                    panelLogin.setVisible(false);
                    enabledMenu();
                    if(vlev_user.equals("Administrator")){
                        
                    }else if(vlev_user.equals("Staff Kemahasiswaan")){
                        
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Id.User dan Password salah !");
                }
                        
                
            }catch(SQLException se){
                JOptionPane.showMessageDialog(this, "Error mthod aksi login() :" +se); //catch untuk menampilkan error pada syntax pada try
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JDesktopPane();
        panelLogin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtIdUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenu();
        mnTA = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnJurusan = new javax.swing.JMenuItem();
        mnProdi = new javax.swing.JMenuItem();
        mnMahasiswa = new javax.swing.JMenu();
        mnDataMhs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnLaporanMhs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setPreferredSize(new java.awt.Dimension(857, 532));

        jPanel2.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N

        txtIdUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "ID. User"));
        txtIdUser.setOpaque(false);

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Password"));
        txtPassword.setOpaque(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login-blue.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/small_logout.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN SIAKAD V.1.0.1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-[Sistem Informasi Akademik Oemah Codinger]-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword)
                            .addComponent(txtIdUser)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelLogin.addTab("Login User", new javax.swing.ImageIcon(getClass().getResource("/Icons/Admin-Schoolar-Icon.png")), jPanel2); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon-login.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Informal Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("SISTEM INFORMASI AKADEMIK");

        jLabel6.setFont(new java.awt.Font("Informal Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Sekolah Tinggi Oemah Codinger <STOC>");

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("oemahcodinger.com");

        panelMenu.setLayer(panelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMenu.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMenu.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMenu.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMenu.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelMenu.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblKeterangan.setText("ID User : ....| LEv User : ....");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKeterangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1 - Sistem.png"))); // NOI18N
        mnSystem.setText("Sistem");

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1 - user.png"))); // NOI18N
        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mnSystem.add(mnUser);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/small_logout.png"))); // NOI18N
        mnKeluar.setText("Keluar");
        mnSystem.add(mnKeluar);

        jMenuBar1.add(mnSystem);

        mnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2 - Master.png"))); // NOI18N
        mnMaster.setText("Master");

        mnTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2 - master small.png"))); // NOI18N
        mnTA.setText("Tahun Angkatan");
        mnTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTAActionPerformed(evt);
            }
        });
        mnMaster.add(mnTA);
        mnMaster.add(jSeparator1);

        mnJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2 - master small.png"))); // NOI18N
        mnJurusan.setText("Jurusan");
        mnJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJurusanActionPerformed(evt);
            }
        });
        mnMaster.add(mnJurusan);

        mnProdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2 - master small.png"))); // NOI18N
        mnProdi.setText("Program Studi");
        mnProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdiActionPerformed(evt);
            }
        });
        mnMaster.add(mnProdi);

        jMenuBar1.add(mnMaster);

        mnMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3 - Mahasiswa.png"))); // NOI18N
        mnMahasiswa.setText("Mahasiswa");
        mnMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMahasiswaActionPerformed(evt);
            }
        });

        mnDataMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3 - mahasiswa small.png"))); // NOI18N
        mnDataMhs.setText("Data Mahasiswa");
        mnDataMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataMhsActionPerformed(evt);
            }
        });
        mnMahasiswa.add(mnDataMhs);
        mnMahasiswa.add(jSeparator2);

        mnLaporanMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        mnLaporanMhs.setText("Laporan Data Mahasiswa");
        mnLaporanMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanMhsActionPerformed(evt);
            }
        });
        mnMahasiswa.add(mnLaporanMhs);

        jMenuBar1.add(mnMahasiswa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdiActionPerformed
       IfrProdi fr = new IfrProdi();
       panelMenu.add(fr);
       fr.setVisible(true);
    }//GEN-LAST:event_mnProdiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        aksilogin();    // pemanggilan method aksilogin;
    }//GEN-LAST:event_btnLoginActionPerformed

    private void mnDataMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataMhsActionPerformed
       IFrMahasiswa fr = new  IFrMahasiswa();
       panelMenu.add(fr);
       fr.setVisible(true);
       fr.getDesktopPane().getDesktopManager().maximizeFrame(fr);// agar halaman mhs menjadi full
    }//GEN-LAST:event_mnDataMhsActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
       IfrUser fr = new IfrUser();
       panelMenu.add(fr);
       fr.setVisible(true);
        
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTAActionPerformed
        IfrTahunAngkatan fr = new IfrTahunAngkatan();
       panelMenu.add(fr);
       fr.setVisible(true);
    }//GEN-LAST:event_mnTAActionPerformed

    private void mnJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJurusanActionPerformed
       IfrJurusan fr = new IfrJurusan();
       panelMenu.add(fr);
       fr.setVisible(true);
    }//GEN-LAST:event_mnJurusanActionPerformed

    private void mnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMahasiswaActionPerformed
      
    }//GEN-LAST:event_mnMahasiswaActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        aksilogin();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void mnLaporanMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanMhsActionPerformed

        frlapmahasiswa = new IfrLapMahasiswa();
        panelMenu.add(frlapmahasiswa);
        frlapmahasiswa.setVisible(true);
        
    }//GEN-LAST:event_mnLaporanMhsActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     */
   public static void main(String[] args) throws UnsupportedLookAndFeelException,
           IOException, ClassNotFoundException, InstantiationException, IllegalAccessException{
       try{
           com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Default ","Java Swing", ""); // baris untuk mengganti tema sesual jtato pada lib
           UIManager.setLookAndFeel("com.jtatto.plaf.mcwin.mcWinLookAndFeel");
           SwingUtilities.updateComponentTreeUI(new Frmenu());
       }finally{
           new Frmenu().setVisible(true);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JMenuItem mnDataMhs;
    private javax.swing.JMenuItem mnJurusan;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLaporanMhs;
    private javax.swing.JMenu mnMahasiswa;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnProdi;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JMenuItem mnTA;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JPanel panel;
    private javax.swing.JTabbedPane panelLogin;
    private javax.swing.JDesktopPane panelMenu;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}

/** Agar ebuah form terkoneki dengan data base 
 * deklarasikan Class koneksi ddatabasenya kedalam from tersebut
 * atau buat object koneksi
 */